_BASE_: "base.yaml"
DEBUG: False

MODEL:
  TYPE: 'smallfusionnet'
  IN_CHANNELS: 1
  OUT_CHANNELS: 1
  LOSS_TYPE: 'PowerJaccardLoss'

DATALOADER:
  MULTIMODAL: True
  TIMESERIES_LENGTHS: [3, 1]
  MODALITIES: ['sar', 'opt']
  ENFORCE_PATCH_SIZE: True
