_BASE_: "base.yaml"
DEBUG: False

MODEL:
  TYPE: 'siamconcmultimodal'
  OUT_CHANNELS: 1
  LOSS_TYPE: 'PowerJaccardLoss'

DATALOADER:
  MULTIMODAL: True
  TIMESERIES_LENGTHS: [2, 1]
  MODALITIES: ['sar', 'opt']
